service: service-name

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGO_URI: ${file(./config.yml):MONGO_URI}
    JWKS_URI: ${file(./config.yml):JWKS_URI}
    AUDIENCE: ${file(./config.yml):AUDIENCE}
    TOKEN_ISSUER: ${file(./config.yml):TOKEN_ISSUER}
    API_GATEWAY_ARN: ${file(./config.yml):API_GATEWAY_ARN}

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true
          authorizer:
            name: authenticate
            resultTtlInSeconds: 3600
            identitySource: method.request.header.Authorization
            identityValidationExpression: '^Bearer [-0-9a-zA-z\.]*$'
            type: token

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  authenticate:
    handler: handler.authenticate
