service: question-service

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGO_URI: ${file(./config.yml):MONGO_URI}
    JWKS_URI: ${file(./config.yml):JWKS_URI}
    AUDIENCE: ${file(./config.yml):AUDIENCE}
    TOKEN_ISSUER: ${file(./config.yml):TOKEN_ISSUER}
    API_GATEWAY_ARN: ${file(./config.yml):API_GATEWAY_ARN}

functions:

  getQuestions:
    handler: handler.getQuestion
    events:
      - http:
          path: questions
          method: get
          cors: true

  getQuestion:
    handler: handler.getQuestion
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  createQuestion:
    handler: handler.createQuestion
    events:
      - http:
          path: questions
          method: post
          cors: true
#          authorizer:
#            name: authenticate
#            resultTtlInSeconds: 3600
#            identitySource: method.request.header.Authorization
#            identityValidationExpression: '^Bearer [-0-9a-zA-z\.]*$'
#            type: token

  updateQuestion:
    handler: handler.updateQuestion
    events:
      - http:
          path: questions/{id}
          method: put
          cors: true

  deleteQuestion:
    handler: handler.deleteQuestion
    events:
      - http:
          path: questions/{id}
          method: delete
          cors: true

#  authenticate:
#    handler: handler.authenticate
